# Mathematical functions

In [3]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

## Trigonometric functions

Calculate sine, cosine, and tangent of x, element-wise.  
Hint: use np.sin(), np.cos(), np.tan()

In [8]:
x = np.array([0., 1., 30, 90])
print(f"Sin is: {np.sin(x)}")
print(f"Cos is: {np.cos(x)}")
print(f"Tan is: {np.tan(x)}")

Cos is: [ 1.          0.54030231  0.15425145 -0.44807362]


array([ 0.        ,  1.55740772, -6.4053312 , -1.99520041])

Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.  
Hint: use np.arcsin(), np.arccos(), np.arctan()

In [4]:
x = np.array([-1., 0, 1.])
print(f"Inverse sin is: {np.arcsin(x)}")
print(f"Inverse cos is: {np.arccos(x)}")
print(f"Inverse tan is: {np.arctan(x)}")

Inverse sin is: [-1.57079633  0.          1.57079633]
Inverse cos is: [3.14159265 1.57079633 0.        ]
Inverse tan is: [-0.78539816  0.          0.78539816]


Convert angles from radians to degrees.  
Hint: use np.degrees() or np.rad2deg()

In [5]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
np.degrees(x)

array([-180.,  -90.,   90.,  180.])

Convert angles from degrees to radians.  
Hint: use np.radians() or np.deg2rad()

In [6]:
x = np.array([-180.,  -90.,   90.,  180.])
np.radians(x)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

## Hyperbolic functions

Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.  
Hint: use np.sinh(), np.cosh(), np.tanh()

In [7]:
x = np.array([-1., 0, 1.])
print(f"Hyperbolic sine is: {np.sinh(x)}")
print(f"Hyperbolic cosine: {np.cosh(x)}")
print(f"hyperbolic tangent is: {np.tanh(x)}")

Hyperbolic sine is: [-1.17520119  0.          1.17520119]
Hyperbolic cosine: [1.54308063 1.         1.54308063]
hyperbolic tangent is: [-0.76159416  0.          0.76159416]


## Rounding

Round x element-wise  
Hint: use np.around(x) or np.floor(x) or np.ceil(x) or np.trunc(x)

In [10]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])
print(f"np.around is {np.around(x)}")
print(f"np.floor is {np.floor(x)}")
print(f"np.ceil is: {np.ceil(x)}")
print(f"np.trunc is: {np.trunc(x)}")


np.around is [ 2.  2.  2.  3. -2. -2. -3.]
np.floor is [ 2.  1.  2.  2. -3. -3. -3.]
np.ceil is: [ 3.  2.  3.  3. -2. -2. -2.]
np.trunc is: [ 2.  1.  2.  2. -2. -2. -2.]


## Sums, products, differences

Calculate the difference between neighboring elements, element-wise.  
Hint: use np.diff()

In [11]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])

Return the cross product of x and y.  
Hint: use np.cross()

In [12]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x,y)

array([-3,  6, -3])

## Exponents and logarithms

Compute $e^x$, element-wise.  
Hint: use np.exp()

In [13]:
x = np.array([1., 2., 3.], np.float32)
np.exp(x)

array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)

Calculate exp(x) - 1 for all elements in x.  
Hint: there are np.expm1() and np.exp(), make your own choice and use it properly

In [19]:
x = np.array([1., 2., 3.], np.float32)
print(f"np.expm1() is {np.expm1(x)}")
print(f"exp()-1 with np.exp() is {np.exp(x)-1}")

np.expm1() is [ 1.7182817  6.389056  19.085537 ]
exp()-1 with np.exp() is [ 1.7182817  6.389056  19.085537 ]


Calculate $2^p$ for all p in x.  
Hint: Refer to the lecture. np.exp2() will help, too.

In [21]:
x = np.array([1., 2., 3.], np.float32)
np.exp2(x)

array([2., 4., 8.], dtype=float32)

Compute natural, base 10, and base 2 logarithms of x element-wise.  
Hint: use np.log(), np.log10(), np.log2()

In [22]:
x = np.array([1, np.e, np.e**2])
print(f"Natural log = {np.log(x)}")
print(f"Common log = {np.log10(x)}")
print(f"Base 2 log = {np.log2(x)}")

Natural log = [0. 1. 2.]
Common log = [0.         0.43429448 0.86858896]
Base 2 log = [0.         1.44269504 2.88539008]


## Arithmetic operations

Add x and y element-wise.

In [27]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])
np.add(x,y)

array([0, 0, 0])

Subtract y from x element-wise.

In [24]:
x = np.array([3, 4, 5])
y = np.array(3)
np.subtract(x,y)

array([0, 1, 2])

Multiply x by y element-wise.

In [29]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
np.multiply(x,y)

array([ 3,  0, -5])

Divide x by y element-wise

In [30]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
np.divide(x,y)

array([3.        , 2.        , 1.66666667])

Compute numerical negative value of x, element-wise.

In [32]:
x = np.array([1, -1])
np.negative(x)

array([-1,  1])

Compute the reciprocal of x, element-wise.

In [33]:
x = np.array([1., 2., .2])
np.reciprocal(x)

array([1. , 0.5, 5. ])

Compute $x^y$, element-wise.

In [34]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
np.power(x,y)

array([[ 1,  4],
       [ 3, 16]], dtype=int32)

Compute the remainder of x / y element-wise in two different ways.  
Hint: use np.mod() or `%` operator

In [35]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
np.mod(x,y)

array([1, 0, 1, 1, 0, 1], dtype=int32)

## Miscellaneous

If an element of x is smaller than 3, replace it with 3.  
And if an element of x is bigger than 7, replace it with 7.  
Hint: use array masking

In [36]:
x = np.arange(10)
x[x < 3] = 3
x[x > 7] = 7
print(x)

[3 3 3 3 4 5 6 7 7 7]


Compute the square of x, element-wise.

In [44]:
x = np.array([1, 2, -1])
np.power(x,2)


array([1, 4, 1], dtype=int32)

Compute square root of x element-wise.

In [42]:
x = np.array([1., 4., 9.])
np.sqrt(x)

array([1., 2., 3.])

Compute the absolute value of x.

In [45]:
x = np.array([[1, -1], [3, -3]])
np.absolute(x)

array([[1, 1],
       [3, 3]])

Compute an element-wise indication of the sign of x, element-wise.

In [50]:
x = np.array([1, 3, 0, -1, -3])
np.sign(x)

array([ 1,  1,  0, -1, -1])

ValueError: NumPy boolean array indexing assignment cannot assign 5 input values to the 4 output values where the mask is true